// Code generated by hessian2 enum generator; DO NOT EDIT.
// Date {{ .date }}


package {{.package}}

import (
    "fmt"
    "strconv"
    hessian "github.com/apache/dubbo-go-hessian2"
)


var _{{ .typeName }}Names = {{ .valueNames }}


var _{{ .typeName }}Values = map[{{ .typeName }}]string{
	TestColorEnumRed: "RED",
	TestColorEnumBlue: "BLUE",
	TestColorEnumYellow: "YELLOW",
}

var _{{ .typeName }}Entities = map[string]{{ .typeName }}{
	"RED": TestColorEnumRed,
	"BLUE": TestColorEnumBlue,
	"YELLOW": TestColorEnumYellow,
}


func (e {{ .typeName }}) JavaClassName() string {
	return "{{ .javaClassName }}"
}

func (e {{ .typeName }}) String() string {
	if v, ok := _{{ .typeName }}Values[e]; ok {
		return v
	}

	return strconv.Itoa(int(e))
}

func (e {{ .typeName }}) EnumValue(s string) hessian.JavaEnum {
	if v, ok := _{{ .typeName }}Entities[s]; ok {
		return hessian.JavaEnum(v)
	}

	return hessian.InvalidJavaEnum
}

func New{{ .typeName }}(s string) {{ .typeName }} {
	if v, ok := _{{ .typeName }}Entities[s]; ok {
		return v
	}

	return {{ .typeName }}(hessian.InvalidJavaEnum)
}

func init() {
	for v := range _{{ .typeName }}Values {
		hessian.RegisterJavaEnum(v)
	}

}



